name: Health app E2E Tests

on:
  push:
    branches: [ main, master ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          cd healthapp
          npm ci
          cd ../healthapp-tests
          npm ci
          npx playwright install --with-deps
      - name: Run tests
        run: |
          cd healthapp
          npm start &
          cd ../healthapp-tests
          npm test
